version: '3'

services:
  notes-app:
    build: ./notes-app
    ports: 
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/notesapp
    command: stack run
    networks:
      - default_network
    dns:
      - "8.8.8.8" 
      - "8.8.4.4"
      - "127.0.0.11"
    depends_on:
      - postgres

  postgres:
    image: postgres:15.3-alpine3.18
    volumes: 
      - ./storage/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notesapp
      - POSTGRES_PORT=5432
    ports: 
      - "5432:5432"
    dns:
      - "8.8.8.8" 
      - "8.8.4.4"
      - "127.0.0.11"
    expose:
      - 5432
    networks:
      - default_network

networks:
  default_network:
